### ISSUE TITLE
Useradd?

### ISSUE THREAD

**Issue by MggMuggins** [redox-os/userutils#16]
Is there a useradd command? I'm probably not looking in the right place, but it seems like a fairly important base functionality.

**Comment by jackpot51** [comment]
No, it is not implemented yet

**Comment by MggMuggins** [comment]
Fantastic! I'll see what I can do... :P

**Comment by jackpot51** [comment]
Sweet!

**Comment by MggMuggins** [comment]
Quick question: Digigng through the source code for the useradd, as well as the man pages, there is a config file located at `/etc/default/useradd`. This allows you to configure what happens when you run useradd. Should I be wary of creating configurations files for utils like this, or is it fine to go ahead and do that?

**Comment by jackpot51** [comment]
If it seems necessary, then it is ok to have a configuration file

**Comment by MggMuggins** [comment]
A second less quick question. How does one go about setting up a development environment for any of these little modules? I've built the kernel from source, is there a better/automated way to get one of these little guys up and running under a Redox system?

**Comment by jackpot51** [comment]
Make modifications in cookbook/recipes/userutils/source

Then run
```
touch filesystem.toml
make qemu
```

**Comment by MggMuggins** [comment]
Awesome, that is really cool. Now I'm wondering if there is any good way to get things set up for just the "users" library. I've already made some simple modifications, but those don't need to be saved (aka, can be copy/pasted). I don't see it in there. Sorry for being so needy...

**Comment by jackpot51** [comment]
Change the Cargo.toml to have
```
users = { path = "/path/to/users” }
```

**Comment by MggMuggins** [comment]
Thank you! Should have a PR some time in the next 8-10 hours.

**Comment by jackpot51** [comment]
Awesome!

**Comment by MggMuggins** [comment]
I'm still really confused by the build system. I've made some headway on the problem I'm trying to solve, but still not understanding how to get that code shipped to a vm so I can test it. Is there any documentation anywhere that you could link me to? I'm also on the IRC (SamwiseFilmore) if you're interested in helping me over there...

**Comment by MggMuggins** [comment]
Well, I won't have a PR for you in 8-10 hours :P

I'm having a strange issue. I added a line via some rust to `/etc/group`, like this: 
`my_group;100;user`
Even though `/etc/group` hasn't appeared to have changed, my error for "that group already exists" is coming up. I've inspected the whole call stack for figuring out if a group exists, and it doesn't make much sense. I can push my changes up to github if you'd like.

**Comment by jackpot51** [comment]
Yes, I would like to see the code

**Comment by MggMuggins** [comment]
Alright, the actual code that does the adding is committed to [MggMuggins/users](https://github.com/MggMuggins/users). My groupadd command basically does this (along with some boilerplate and error handling for an empty args[0]).

```Rust
let groupname = &parser.args[0];
match add_group(groupname, 100, &["user"]) {
    Ok(_) => {},
    Err(err) => eprintln!("groupadd: {}: {}", err, groupname)
}
```

**Comment by jackpot51** [comment]
I would like to see what is output if you add this inside add_group:

```rust
    for group in groups {
        println!("add_group({}, {}, {:?}): Group {}, {}", name, gid, users, group.group, group.gid);
        if group.group == name || group.gid == gid {
            return Err("group already exists");
        }
    }
```

**Comment by MggMuggins** [comment]
I've finally got this to a point where it works, and is fairly robust. Thanks for the help with this one jackpot, really helpful for an entry-level programmer!
